version: '2'
services:
  unifi:
    image: rafikn/unifi:4.8.12
    ports:
    - "8443:8443"
    - "8080:8080"
    - "8081:8081"
    - "3478:3478"
    volumes:
    - /opt/UniFi/data:/opt/unifi/data:rw
